import { useEffect, useMemo, useState } from "react";
import "./sellerAdmin.css";

const money = (v) => Number(v || 0).toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
export default function SellerAdminPage({ apiRequest }) {
  const [sellers, setSellers] = useState([]); const [commissions, setCommissions] = useState([]); const [feedback, setFeedback] = useState("");
  const [form, setForm] = useState({ name: "", email: "", phone: "", code: "", password: "", calculationType: "percentage", commissionValue: "12", recurrenceType: "recurring" });
  async function load() { try { const [s, c] = await Promise.all([apiRequest("/admin/sellers"), apiRequest("/admin/seller-commissions")]); setSellers(s.data || []); setCommissions(c.data || []); } catch (e) { setFeedback(e.message); } }
  useEffect(() => { load(); }, []);
  const totals = useMemo(() => ({ pending: commissions.filter(x => x.status === "pending").reduce((a,x)=>a+Number(x.commissionAmount),0), approved: commissions.filter(x => x.status === "approved").reduce((a,x)=>a+Number(x.commissionAmount),0), paid: commissions.filter(x => x.status === "paid").reduce((a,x)=>a+Number(x.commissionAmount),0) }), [commissions]);
  async function createSeller(e) { e.preventDefault(); try { await apiRequest("/admin/sellers", { method: "POST", body: JSON.stringify(form) }); setForm({ ...form, name:"",email:"",phone:"",code:"",password:"" }); setFeedback("Vendedor criado com sucesso."); await load(); } catch(e){ setFeedback(e.message); } }
  async function changeStatus(id, status) { await apiRequest(`/admin/seller-commissions/${id}/status`, { method:"PATCH", body:JSON.stringify({status}) }); await load(); }
  async function payCommission(id) { const paymentMethod = window.prompt("Forma de pagamento da comissão:", "PIX"); if (!paymentMethod) return;
    const notes = window.prompt("Observação do pagamento (opcional):", "") || "";
    try { await apiRequest("/admin/seller-commissions/pay", { method:"POST", body:JSON.stringify({ commissionIds:[id], paymentMethod, notes, paidAt:new Date().toISOString() }) }); setFeedback("Comissão marcada como paga."); await load(); } catch(e){ setFeedback(e.message); } }
  function copy(link) { navigator.clipboard.writeText(link); setFeedback("Link copiado."); }
  return <section className="seller-admin-page"><header><div><span>VENDAS E PARCERIAS</span><h2>Vendedores e comissões</h2><p>Acompanhe indicações, clientes e pagamentos em um só lugar.</p></div></header>
    {feedback && <div className="seller-feedback">{feedback}</div>}<div className="seller-kpis"><article><span>Vendedores ativos</span><strong>{sellers.filter(x=>x.status==="active").length}</strong></article><article><span>Comissão pendente</span><strong>{money(totals.pending)}</strong></article><article><span>Aprovada</span><strong>{money(totals.approved)}</strong></article><article><span>Total pago</span><strong>{money(totals.paid)}</strong></article></div>
    <div className="seller-admin-grid"><form className="seller-panel seller-form" onSubmit={createSeller}><h3>Novo vendedor</h3><label>Nome<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>E-mail<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>WhatsApp<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>Código<input required placeholder="MARIA001" value={form.code} onChange={e=>setForm({...form,code:e.target.value.toUpperCase()})}/></label><label>Senha de acesso<input required type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><div className="seller-form-row"><label>Tipo<select value={form.calculationType} onChange={e=>setForm({...form,calculationType:e.target.value})}><option value="percentage">Porcentagem</option><option value="fixed">Valor fixo</option></select></label><label>Valor<input type="number" step="0.01" value={form.commissionValue} onChange={e=>setForm({...form,commissionValue:e.target.value})}/></label></div><label>Recorrência<select value={form.recurrenceType} onChange={e=>setForm({...form,recurrenceType:e.target.value})}><option value="recurring">Todos os pagamentos</option><option value="first_payment">Somente primeira mensalidade</option></select></label><button>Salvar vendedor</button></form>
      <div className="seller-panel"><h3>Equipe comercial</h3><div className="seller-list">{sellers.map(s=><article key={s.id}><div><strong>{s.name}</strong><span>{s.code} · {s.customers} clientes · {s.clicks} cliques</span></div><div className="seller-row-actions"><button onClick={()=>copy(s.link)}>Copiar link</button><a href={`https://wa.me/?text=${encodeURIComponent(`Conheça o ViaPet: ${s.link}`)}`} target="_blank" rel="noreferrer">WhatsApp</a></div></article>)}{!sellers.length&&<p>Nenhum vendedor cadastrado.</p>}</div></div></div>
    <div className="seller-panel"><h3>Comissões</h3><div className="seller-table"><div className="head"><span>Data</span><span>Vendedor</span><span>Cliente</span><span>Mensalidade</span><span>Comissão</span><span>Status</span><span>Ação</span></div>{commissions.map(c=><div key={c.id}><span>{new Date(c.createdAt).toLocaleDateString("pt-BR")}</span><span>{c.sellerName}</span><span>{c.customerName}</span><span>{money(c.paymentAmount)}</span><strong>{money(c.commissionAmount)}</strong><span>{c.status}</span><span>{c.status==="pending"?<button onClick={()=>changeStatus(c.id,"approved")}>Aprovar</button>:c.status==="approved"?<button onClick={()=>payCommission(c.id)}>Pagar</button>:"—"}</span></div>)}</div></div>
  </section>;
}
